### ISSUE TITLE
Issues with props rest spread operator

### ISSUE THREAD

**Issue by bcarroll22** [vuejs/babel-plugin-transform-vue-jsx#1]
Hey Vue team,

Very nice work on everything with 2.0. So far, it's been awesome to use!

I just tried to use the spread operator with props, and I'm getting an error. I've verified that the spread operator is working correctly in other places, and I've also verified that the props are being passed in correctly.

Here's the error that I am getting:

![screen shot 2016-06-18 at 8 39 01 pm](https://cloud.githubusercontent.com/assets/11020406/16174567/ee63fb50-3594-11e6-9556-2222d518c3db.png)

Thanks again for the great work with 2.0!

**Comment by bcarroll22** [comment]
I also just verified that the spread operator works when manually building the hypertext function:
```
h(Grandchild, {
  props: {
    ...props
  }
})
```
I did a little digging, and it looks like when using the spread operator, the attribs that get passed into `buildOpeningElementAttributes` is undefined.

**Comment by bcarroll22** [comment]
Actually, testing even further up the chain, it looks like I can try to `console.log(path)` in the `JSXElement` property of the export return, and for the component with the spread operator the path is undefined. For reference, I'm just doing `<Grandchild {...props} />`

**Comment by yyx990803** [comment]
JSX spread puts all properties in the spread object as top-level properties, so they are not nested under `props`. You will need to do `<Grandchild {...{ props }} />` to ensure it's nested.

We may do some more exploration on how spread should work for Vue's vnode format though, since this seems to going be a common gotcha.

**Comment by bcarroll22** [comment]
I see, isn't spreading at the top level still valid with Vue though? How does the jsx parser handle me putting the props at the top level? What I mean is, this works:
```
<Child test={'hello'} otherTest={'world'} />
```
This doesn't 
```
<Child {...props} />
```
But wouldn't they produce the same output? Or does the parser somehow know to put test and otherTest in props?

**Comment by yyx990803** [comment]
The nesting is determined at syntax level but the spread is actually done
via a runtime extend helper, so they are different.

**Comment by blocka** [comment]
I'm trying to do something like this

`<Link to={somewhere} style={{color: 'red'}}>A link</link>`

Where I want `Link`, a functional component, to render an `a` tag with the given attributes passed in.

I noticed that the `style` object is being passed in as `data` so I tried:

`return <a href={to} {...data}>{children()}</a>`

However,  that throws out the `href`.

trying `<a href={to} {...{ data }}>{children()}</a>` the style attribute doesn't get through and

`<a href={to} {...{ ...data }}>{children()}</a>` gives me a syntax error.

**Comment by yyx990803** [comment]
1.1.0 now has improved JSX spread support - just spread it with `{...data}` and it will merge them properly.

**Comment by blocka** [comment]
Still having some issues

`<Component {...props}></Component>`

renders as 

```
return h(
      'div',
      null,
      [h(
        Component,
        props,
        function () {
          return [];
        }
      )]
```

and `<Component {...{ props }}></Component>`

renders as 
```
return h(
      'div',
      null,
      [h(
        Component,
        {
          attrs: { props: props }
        }
```

**Comment by yyx990803** [comment]
You need to spread to top-level data object, not props.

**Comment by blocka** [comment]
So how would I do this with props, exactly?

**Comment by yyx990803** [comment]
...{{ props }}

**Comment by blocka** [comment]
For the record, this worked (basically what I see you've done in the test), although I'm not 100% happy with it (can't complain too much).

```
const data = {props};

return <Component {...data}></Component>
```

This did not though (props did not get passed through):

```
return <Component {...{props}}></Component>
```

**Comment by yyx990803** [comment]
@blocka indeed, fixed in 1.1.1

**Comment by ArmorDarks** [comment]
Does it works for anyone?

It seems that it works again only when passed as `{...{props}}`

**Comment by ArturoWipe** [comment]
Neither `{...props}` nor `{...{props}}` worked for me
