### ISSUE TITLE
about the use of "on" events handlers

### ISSUE THREAD

**Issue by ervinewell** [vuejs/babel-plugin-transform-vue-jsx#100]
As Pagination of ElementUI components, they bind the event of changing current page number with a hyphenated word "current-change":
`<el-pagination @current-change="currentChangeHandler"></el-pagination>`
When tranformed to JSX in Vue, the codes becomes to:
 `<Pagination onCurrent-change />`
In addition, writing `onCurrentChange` won't be effective. I suppose if we can optimize the style of writing? 
Good day.

**Comment by nickmessing** [comment]
@ervinewell `on-current-change` will work just fine too

**Comment by njleonzhang** [comment]
both `onCurrent-change ` and `on-current-change` don't work, I need to write in this way:

```
render() {
  let listeners = {
     current-change: this.method
  }
   
  return (
     <Component {...{on: listeners}}>
  )
}
```

```
    "vue": "^2.5.2",
    "babel-plugin-syntax-jsx": "^6.18.0",
    "babel-helper-vue-jsx-merge-props": "^2.0.2",
    "babel-plugin-transform-vue-jsx": "^3.5.0"
```

Can `vue` team make the doc more detailed?

**Comment by nickmessing** [comment]
@njleonzhang, how come `on-current-change` doesn't work? Can you please provide an example using [codepan](https://codepan.net/)?

**Comment by njleonzhang** [comment]
would you please provide a boilerplate?

**Comment by Atuna** [comment]
I have an event like this: 'vuetable-pagination:change-page'. （Pay attention to the colon）
Is it possible to bind this event via JSX?

**Comment by njleonzhang** [comment]
@Atuna can it work in this way?
```
render() {
  let listeners = {
      'vuetable-pagination:change-page': this.method
  }
   
  return (
     <Component {...{on: listeners}}>
  )
}
```
