### ISSUE TITLE
Change in the compilation of the value attribute

### ISSUE THREAD

**Issue by matfish2** [vuejs/babel-plugin-transform-vue-jsx#101]
I have built a grid component using this compiler about a year ago. 
In order to make the filters more effective I've applied a debounce timeout to the search function.
I've recently noticed that when the search function is running, the query value is being reattached to the `input` element when I assign it. This causes an interference, because if the user typed some characters in the short time slot just after the timeout, but before the query was assigned, the original query will override them.

After some exploration I found that this package has changed the way it deals with the `value` attribute (582b4a60e79884f6722b6c3cd9cd74cc13741d66), namely, if the value is a jsx expression it is no longer registered on the `attrs` property, but instead added to `domProps`. 

If I understand correctly this is the source of my problem, i.e, `value` as an attribute in only assigned initially, while as a dom property it is bound to the model, and updates the view every time the model has changed.

Is there a way to bind a jsx expression to the value without the Model->View binding?

**Comment by nickmessing** [comment]
@matfish2, you can just use debounce inside a [watcher](https://vuejs.org/v2/guide/computed.html#Watchers) and keep a part of your component state always in sync (just like v-model) so you don't have to use logic (debounce) inside your render function (that's always a good idea).
