### ISSUE TITLE
JSX spread props, mixed syntax

### ISSUE THREAD

**Issue by Astray-git** [vuejs/babel-plugin-transform-vue-jsx#105]
The `createElement` second argument  'data object' syntax is different from 'Vue 2.0 JSX' syntax.

This works:
```jsx
/* createElement data object  */
const data = {
  attr: {
    id: 'b'
  }
}
/* vue jsx */
const vnode = <div class="a" {...data}/>
```
This doesn't:
```jsx
/* jsx prop obj  */
const props = {
  id: 'b'
}
/* jsx */
const vnode = <div class="a" {...props}/>
```
I can't use pure JSX syntax and have to mix some `createElement` argument in render function, kinda weird.

**Comment by njleonzhang** [comment]
@Astray-git you need write in this way:

```
/* jsx prop obj  */
const props = {
  id: 'b'
}
/* jsx */
const vnode = <div class="a" {...{props: props}}/>
```

**Comment by fnlctrl** [comment]
Thanks @njleonzhang for the explanation!
There're many small differences between vue/react's `createElement` arguments, please refer to https://github.com/vuejs/babel-plugin-transform-vue-jsx#difference-from-react-jsx

**Comment by njleonzhang** [comment]
@fnlctrl  Yeah, it's confusing sometimes.

**Comment by Astray-git** [comment]
`{...{props: props}}` this part still enforce `createElement` arguments.

@fnlctrl  The confusing part is vue's jsx props is different from vue's `createElement` arguments, while in react, jsx and `createElement` share a same arguments.
