### ISSUE TITLE
scopedSlots incorrect h var injection

### ISSUE THREAD

**Issue by andreiglingeanu** [vuejs/babel-plugin-transform-vue-jsx#107]
### Version
2.5.8

### Reproduction link
[https://github.com/andreiglingeanu/vue-duplicated-h-reproduction](https://github.com/andreiglingeanu/vue-duplicated-h-reproduction)

### Steps to reproduce
1. `yarn && yarn run dev`
2. Observe the error in devtools JS console

Here's the relevant code generated by the transformer:

```javascript
  render: function render(h) {
    var vm = this;

    return h(
      __WEBPACK_IMPORTED_MODULE_1__App_js__["a" /* default */],
      {
        scopedSlots: {
          default: function _default(_ref) {
            var text = _ref.text;
            // This line should be skipped
            var h = this.$createElement;

            // return vm.$createElement('div', text)
            return h(
              'div',
              null,
              [props.text]
            );
          }
        }
      },
      []
    );
  }

```

### What is expected?
To not generate an additional `var h = this.$createElement;`. This won't work primarily because the this in the `scopedSlots` function is not what will someone expect.

### What is actually happening?
`h` is injected incorrectly.

<hr>

That could be fixed in user land in two ways:

1. Just use an arrow function or `.bind(this)`
2. Create a reference to `self` and use `self.$createElement` calls instead of JSX, which is very inconvenient.

Both of them would be easily fixable by just skipping a repeated, nested version of `var h`. I understand that detecting this edge-case might be a bit tricky but it would be a boost in user experience, in my opinion.

**Comment by LinusBorg** [comment]
@nickmessing this might be something for your type of skills.

**Comment by andreiglingeanu** [comment]
Thanks!
