### ISSUE TITLE
could you please support real functional?

### ISSUE THREAD

**Issue by yozman** [vuejs/babel-plugin-transform-vue-jsx#113]
`react`
```jsx
const component = props => (
  <react />
);
```

`vue`
```javascript
const component = {
  functional: true,
  render: function (createElement, context) {
    // ...
  },
};
```

`react` way is write function and can use like function `{component(props)}`,
but `vue` is writing `object`!!!

**Comment by yyx990803** [comment]
https://github.com/nickmessing/babel-plugin-jsx-vue-functional

**Comment by yozman** [comment]
@yyx990803 
it's hack and [some problem](https://github.com/nickmessing/babel-plugin-jsx-vue-functional#warning) as it's `README.md`
I think the right way is `Vue` support functional way to `define` a component like this
```javascript
// now
const component = {
  template: ``,
  render(h) {},
};

// should be
const component = (context) => ({
  template: ``,
  render(h) {},
});
```

**Comment by tereaksmey123** [comment]
+1 support real functional for JSX in vue 👍
