### ISSUE TITLE
support props .sync

### ISSUE THREAD

**Issue by njleonzhang** [vuejs/babel-plugin-transform-vue-jsx#114]
is there a plan to support `.sync`?

**Comment by njleonzhang** [comment]
I have made a babel plugin to support this feature.  [babel-plugin-vue-jsx-sync](https://github.com/njleonzhang/babel-plugin-vue-jsx-sync)
online demo:  https://njleonzhang.github.io/babel-plugin-vue-jsx-sync/

**Comment by ZengTianShengZ** [comment]
厉害了 👍

**Comment by nickmessing** [comment]
@njleonzhang, there is https://github.com/nickmessing/babel-plugin-jsx-event-modifiers, but I will figure a way to make it a part of this repo later.

**Comment by FuDesign2008** [comment]
> @njleonzhang, there is https://github.com/nickmessing/babel-plugin-jsx-event-modifiers, but I will figure a way to make it a part of this repo later.

Is all going well?
