### ISSUE TITLE
[Bug] Component are re-rendered even if not needed 

### ISSUE THREAD

**Issue by titouancreach** [vuejs/babel-plugin-transform-vue-jsx#115]
Given 2 very simple child components

MyInput.jsx
```jsx
export default {
  props: ['update', 'value'],
  
  render(h) {
    return (
      <div>
       <input value={this.value} onInput={this.update} />
      </div>
    );
  }
};
```

and 
Foobar.jsx

```jsx
export default {
  updated() {
    console.log('FOOBAR is updated');
  },

  render(h) {
    return (
      <div>
       FOOBAR
      </div>
    );
  }
};
```

And the wrapper component:

```jsx
export default {
  data: () => ({
    value: 'myval'
  }),

  methods: {
    update(v) {
      this.value = v;
    }
  },
  
  render(h) {
    return (
      <div>
       <MyInput value={this.value} update={this.update} />
       <Foobar />
      </div>
    );
  }
};
```

Each time my value in the input is updated, then, the message: `FOOBAR is updated` is displayed.
It make no sence to re-render FooBar component that depends on no props.

Template version doesn't rerender Foobar:

```html
<template>
  <div>
    <MyInput :update=update :value=value />
    <FooBar />
  </div>
</template>
```
 `FOOBAR is updated` is not displayed.

The `h` version also work:

```jsx
render(h) {
  return h('div', [
    h('FooBar'),
    h('MyInput', {props: {value: this.value, update: this.update}})
  ]);
};
```
That look very weird because I thought the JSX version compile into my `h` version. This bug makes all my child components to be rerender even if they don't need. 

Update: I noticed that:
```
  h('Foobar', [])
```
Display the message whereas
```
  h('Foobar')
```
Work as expected.
I don't know why the behavior is different in this case, I'll also open an issue in Vue.

**Comment by LinusBorg** [comment]
Please provide a repository with a runnabe reproduction. We can't rely on re-building your example to find the bug we have, or mistake you did.

**Comment by titouancreach** [comment]
Here is a repro: https://codepen.io/anon/pen/dJpomx?editors=1011

**Comment by titouancreach** [comment]
This PR should fix the issue right ? https://github.com/vuejs/babel-plugin-transform-vue-jsx/pull/103

**Comment by nickmessing** [comment]
It produces:
```
  render: function render(h) {
    return h(
      'div',
      null,
      [h(MyInput, {
        attrs: { value: this.value, update: this.update }
      }), h(Foobar, null)]
    );
  }
```
so no empty array is created, I have no idea why it re-renders :smile:

**Comment by LinusBorg** [comment]
It seem to me that #92 should have fixed that..

**Comment by nickmessing** [comment]
@LinusBorg, it would fix if it was "empty array" problem, but it's not :cry:

**Comment by titouancreach** [comment]
Do you want a git repo to test it ?

**Comment by titouancreach** [comment]
@nickmessing Are you sure it produces the code of your comment ?
 
```javascript
  render: function render(h) {
    return h(
      'div',
      null,
      [h(MyInput, {
        attrs: { value: this.value, update: this.update }
      }), h(Foobar, null)]
    );
  }
```

Because changing the render function to this on the pen doesn't update Foo, whereas the  repository does.

Here is the component extracted from the bundled version of the repro repository:

```javascript
exports.default = {
  name: 'MyView',

  components: {
    Foobar: _Foobar2.default,
    MyInput: _MyInput2.default
  },

  data: function data() {
    return {
      value: 'Test'
    };
  },

  methods: {
    update: function update(v) {
      this.value = v;
    }
  },

  render: function render() {
    var h = arguments[0];

    return h(
      "div",
      null,
      [h(
        "div",
        null,
        ["REPRODUCTION"]
      ), h(
        _MyInput2.default,
        {
          attrs: { value: this.value, update: this.update }
        },
        []
      ), h(
        _Foobar2.default,
        null,
        []
      )]
    );
  }
};
},{"./Foobar.jsx":4,"./MyInput.jsx":5}],2:[function(require,module,exports) {
"use strict";

```

Foo bar does have an empty child.

**Comment by titouancreach** [comment]
Maybe the problem is just that the PR that has been merged to master, has not been published on NPM ?
[Commit history](https://github.com/vuejs/babel-plugin-transform-vue-jsx/commits/master) and [NPM](https://www.npmjs.com/package/babel-plugin-transform-vue-jsx) shows that the last NPM version is 3.5.0 (pushed in 6 month ago). My reproduction repository use the NPM version (without the PR merged). 
In this case, we just need to publish the new version to NPM.

**Comment by andtii** [comment]
Any updates in this issue? Im runnibg the latest vue version but has this issue aswell!

**Comment by sant123** [comment]
The version `3.5.1` has been released on NPM 9 days ago, do you still have this issue @titouancreach?

**Comment by titouancreach** [comment]
I updated the repro repository with the new version:
  - https://github.com/titouancreach/repro-babel-plugin-transform-vue-jsx--115
Foo is not re-rendered anymore, looks good to me!

I close the issue.

Thanks, you rocks!
