### ISSUE TITLE
How do I get this to play with eslint?

### ISSUE THREAD

**Issue by blocka** [vuejs/babel-plugin-transform-vue-jsx#12]
```
const Component = {....}

.....

<Component></Component>

```

eslint complains that `Component` is never used.

I tried adding 

```
  "parserOptions": {
    "ecmaFeatures": {
      "jsx": true
    }
  },
```

to .eclintrc.js, but that didn't seem to help.

**Comment by blocka** [comment]
This seems to do the trick: https://www.npmjs.com/package/eslint-plugin-react

**Comment by skyrpex** [comment]
Yeah, it does. Thanks for pointing out :+1:

This should be closed.
