### ISSUE TITLE
vuejs ref attribute

### ISSUE THREAD

**Issue by acgentry** [vuejs/babel-plugin-transform-vue-jsx#120]
Okay possibly an idiotic question, but is there a way in a JSX file to transpile the vuejs [ref](https://vuejs.org/v2/api/#ref) attribute without the system thinking its a component?

Thanks!
acgentry

**Comment by nickmessing** [comment]
Please do not use github issues for questions. There is [forum](https://forum.vuejs.org) and [chat](https://chat.vuejs.org) designed for that.
