### ISSUE TITLE
How to set complex object to attribues

### ISSUE THREAD

**Issue by andtii** [vuejs/babel-plugin-transform-vue-jsx#121]
In vue templates you can set complex obects to attribute using 

<my-comp :myprop.prop="{my: "data"}" />

but i cant find how to do this with jsx?

<my-comp myprop={{my: "data"}}" />  is setting the object on the attribute in the dom and there will be a [Object object] passed which will not be accessible

Any ideas @ktsn or @LinusBorg

**Comment by LinusBorg** [comment]
It seems you are talking about domProps, not attributes.

DomProps aren't supported by this plugin, I think. React doesn't have such a feature and the JSX spec therefore doesn't have a syntax for it as well.

Similarly, event modifiers (e.g. `@click.prevent`) isn't supported.

@nickmessing created a transform for the latter: [babel-plugin-jsx-event-modifiers](https://github.com/nickmessing/babel-plugin-jsx-event-modifiers), maybe he has an idea?

**Comment by nickmessing** [comment]
@andtii, to bind to domProp you can simply prepend it with `domProp-` so it is like `domProp-myprop`. That should do the trick.

**Comment by LinusBorg** [comment]
Oh, totally missed that nick thanks.

**Comment by andtii** [comment]
Thnx @nickmessing it worked using domProps-myprop and the domProps is documentet here
 https://github.com/vuejs/babel-plugin-transform-vue-jsx
but missing the dash in the documentation for it.

**Comment by nickmessing** [comment]
That is because dash is not required, I just like it :)
