### ISSUE TITLE
Vue指令没有value值用jsx语法怎么写？

### ISSUE THREAD

**Issue by yangerlang** [vuejs/babel-plugin-transform-vue-jsx#129]
`<el-button style="font-size: 12px;" type="text" v-popover:popover4>编辑</el-button>` 这个里面的v-popover:popover4 这条指令jsx语法应该怎么写才行？？ 
我写成  `<el-button style="font-size: 12px;" type="text" v-popover={{popover4, modifier:true}}>编辑</el-button>`我这样写不行呢！！

`const directives = [
                    { name: 'popover',  modifiers: { popover4: true } }
                ];
 <el-button style="font-size: 12px;" type="text" {...{ directives }}>编辑</el-button>`

 我这样写也不行！！
最后错误信息：
![image](https://user-images.githubusercontent.com/16792231/37817529-07613524-2eb2-11e8-8375-e730c111ae32.png)

**Comment by mengxiong10** [comment]
参数错了
```JavaScript
    const directives = [
      { name: 'popover4',  arg: 'popover4' }
    ]
```

**Comment by fnlctrl** [comment]
同上，见https://github.com/vuejs/babel-plugin-transform-vue-jsx#vue-directives
