### ISSUE TITLE
Using Vue JSX inside jsfiddle/codepen demo

### ISSUE THREAD

**Issue by p-adams** [vuejs/babel-plugin-transform-vue-jsx#13]
Is it possible to use Vue JSX inside a jsfiddle or codepen demo? I am trying to use it in codepen. I have the babel preprocessor selected and a cdn to the latest beta of Vue 2.0. But it doesn't seem to work. As it stands now, the only way to play around with Vue JSX is to setup a basic webpack project similar to the example provided in this repo?

**Comment by LinusBorg** [comment]
I think for this to work, Codepen would have to provide a way to add individual settings to the babel config, since you have to tell babel that you use this plugin:
```js
{
  "presets": ["es2015"],
  "plugins": ["transform-vue-jsx"]
}
```

**Comment by p-adams** [comment]
Okay. So I tried use vue cli with vue 2.0 and and `npm install` this stuff here:
  `npm install
  babel-plugin-syntax-jsx\
  babel-plugin-transform-vue-jsx\
  babel-helper-vue-jsx-merge-props\
  --save-dev`

But I got errors and it would not install the plugins. I know Vue 2.0 is not out yet; however, I am eager to start using it with JSX and would like to get started. How do I configure vue-cli so I can easily use the JSX plugin? 

Thanks

**Comment by LinusBorg** [comment]
IF it did not install the plugins, then you had a problem with npm, not Vue. At least that's what I have to assume because you did not mention what errors you had occur.

Installations instructions are in the [README](https://github.com/vuejs/babel-plugin-transform-vue-jsx/blob/master/README.md), if you get stuck you can always ask on the forum.vuejs.org

**Comment by nddery** [comment]
Although a bit finicky, [webpackbin](http://www.webpackbin.com) allows to use JSX. Here's a [basic example](http://www.webpackbin.com/4JgLKCOUz) using Vue and JSX.

You need to configure webpackbin to use Vue and tell babel to support JSX.

<img width="797" alt="screen shot 2017-01-18 at 17 19 57" src="https://cloud.githubusercontent.com/assets/610207/22085604/b5de8f64-dda2-11e6-93d8-d15c9734861e.png">

**Comment by reverland** [comment]
For people who need a simple pure browser based vue playground with jsx support , check [vuep](https://qingwei-li.github.io/vuep/).

Even vuex may be possible with extra effort : )

**Comment by egoist** [comment]
Well, try CodePan 😂 https://codepan.js.org/#/?boilerplate=vue-jsx 100% Vue JSX support.

**Comment by nickmessing** [comment]
@p-adams, as commented above, you can use @egoist's project for that.

**Comment by egoist** [comment]
Just FYI, CodeSandbox has great Vue (including Vue JSX) support: https://codesandbox.io/s/vue

**Comment by mcshaman** [comment]
> Although a bit finicky, [webpackbin](http://www.webpackbin.com) allows to use JSX. Here's a [basic example](http://www.webpackbin.com/4JgLKCOUz) using Vue and JSX.
> 
> You need to configure webpackbin to use Vue and tell babel to support JSX.
> 
> <img alt="screen shot 2017-01-18 at 17 19 57" width="797" src="https://cloud.githubusercontent.com/assets/610207/22085604/b5de8f64-dda2-11e6-93d8-d15c9734861e.png">

The webpackbin link goes to some malicious website. Please kill the link.
