### ISSUE TITLE
how to subscribe events like on-select 

### ISSUE THREAD

**Issue by rawbin-** [vuejs/babel-plugin-transform-vue-jsx#132]
iView: https://www.iviewui.com/components/menu
triggered an event named "on-select" 

in vue template we use @on-select="selectMenu"

how can we subscribe this kind of event.

all of them worked

        // <Menu theme="light" accordion={this.accordion} style={this.styleObj} {...{on:{"on-select":this.selectMenu}}} >
        // <Menu theme="light" accordion={this.accordion} style={this.styleObj} onOn-select={this.selectMenu} >
        // <Menu theme="light" accordion={this.accordion} style={this.styleObj} on-on-select={this.selectMenu} >

**Comment by ShawshankLin** [comment]
iview的select组件为什么用onChange没有触发呢？
