### ISSUE TITLE
use tag tempalte in vue jsx 

### ISSUE THREAD

**Issue by njleonzhang** [vuejs/babel-plugin-transform-vue-jsx#139]
is there a way to use template tag in jsx?
https://vuejs.org/v2/guide/components-slots.html#Named-Slots

**Comment by troy351** [comment]
```html
<ul>
  <template v-for="item in items">
    <li>{{ item.msg }}</li>
    <li class="divider" role="presentation"></li>
  </template>
</ul>
```
is equivalent to
```jsx
<ul>
  {items.map(item => [
    <li>{item.msg}</li>,
    <li class="divider" role="presentation" />,
  ])}
</ul>
```

**Comment by njleonzhang** [comment]
sorry @tory351, I mean the template for slot.
https://vuejs.org/v2/guide/components-slots.html#Named-Slots

```
<base-layoutase-layout>
   <templateemplate slotlot="header"header">
       <h11>Here might be a page titleere might be a page ti </h1>
  </template>

  <p>A paragraph for the main content.</p>
  <p>And another one.</p>

  <template slot="footer">
    <p>Here's some contact info</p>
  </template>
</base-layout>

```

**Comment by troy351** [comment]
Actually multiple element with the same slot name could work as expected
```html
<base-layout>
  <template slot="header">
    <h1>Here might be a page title</h1>
    <h1>Here might be a page title</h1>
  </template>
</base-layout>
```
is equivalent to
```html
<base-layout>
    <h1 slot="header">Here might be a page title</h1>
    <h1 slot="header">Here might be a page title</h1>
</base-layout>
```

**Comment by njleonzhang** [comment]
wooo, Tnx. it seems a workaround for `slot template` in jsx. I will try it later. hope Vue can support `<></>` ASAP.

**Comment by troy351** [comment]
Actually this works in vue template, too

**Comment by njleonzhang** [comment]
@troy351 would you please help to check the following code? 

`el-table` has a slot named `append`.
I have made a component to wrap `el-table`.  To make my component also support slot `append`, I write the code:

```
<div slot='append'>
{
      this.$slots.append
}
</div>
```
https://github.com/njleonzhang/vue-data-tables/blob/c88b916442efb192f66f63f2a27df5b0005641cc/src/mixins/ShareMixin.js#L151

is there anyway to omit the `div`? `template` ?

**Comment by troy351** [comment]
I've tried `<template slot="append">`, seems it works

**Comment by kimamula** [comment]
It is written that the `slot` attribute is [deprecated](https://vuejs.org/v2/guide/components-slots.html#Deprecated-Syntax).

What is the correct way to use named slots in JSX?
