### ISSUE TITLE
Spread operator for intermediary component props

### ISSUE THREAD

**Issue by kushalmahajan** [vuejs/babel-plugin-transform-vue-jsx#161]
Found links #112 not working still. I believe it was fixed in 3.0.4.
I'm using this in my **package.json**

```
 "babel-plugin-transform-vue-jsx": "^3.7.0",
```

Is there possibility to do something of this sort directly

```
 <Button class="mr10">
          <icon name="page-previous-outline" />
        </Button>

        <Button>
          <icon name="page-next-outline" />
        </Button>
```

Then in my component

```

 return (
      <StyledBtn
        {...props}
        onClick={e => listeners.click(e)}
      >
        {title ? title : children}
      </StyledBtn>
    );
```

**babel.config.js**

```
module.exports = {
  presets: ["@vue/app"],
  plugins: ["transform-vue-jsx"]
};
```

**Comment by kushalmahajan** [comment]
Tried this as well - https://forum.vuejs.org/t/how-to-use-spread-operator-for-passing-props-to-components/8222/4?u=kushalvm

**Comment by nickmessing** [comment]
Spread is a little special so you have to do `<tag {...{props}} />` because our VDom structure is not like React's, you can read more [here](https://github.com/vuejs/babel-plugin-transform-vue-jsx#difference-from-react-jsx)
