### ISSUE TITLE
BabelJS Cannot find module 'babel-plugin-syntax-jsx'

### ISSUE THREAD

**Issue by SanjayBanjade** [vuejs/babel-plugin-transform-vue-jsx#167]
I recently updated my project. I did `ncu -a` to upgrade package.json and did `npm i -g webpack-cli --save-dev` and `npm i webpack-cli --save-dev`.

After that I did `babel-upgrade --write --install`. However, I am getting the following error:
```
    Error: [BABEL] /vue-project/src/main.js: Cannot find module 'babel-plugin-syntax-jsx' (While processing: "/vue-project/node_modules/babel-plugin-transform-vue-jsx/index.js")
```

Then did `npm i --save babel-plugin-transform-vue-jsx` which gave me the following errors:
````
    These dependencies were not found:
    
    * @babel/runtime/helpers/asyncToGenerator in ./src/store/modules/menu.js, ./src/store/modules/model.js and 10 others
    * @babel/runtime/helpers/defineProperty in ./src/store/modules/menu.js, ./src/store/modules/model.js and 11 others
    * @babel/runtime/helpers/objectDestructuringEmpty in ./src/store/modules/schema.js, ./src/store/modules/apiurl.js
    * @babel/runtime/helpers/objectSpread in ./src/store/modules/menu.js
    * @babel/runtime/helpers/slicedToArray in ./src/store/modules/builder.js
    * @babel/runtime/helpers/toConsumableArray in ./src/store/modules/menu.js
    * @babel/runtime/regenerator in ./src/store/modules/menu.js, ./src/store/modules/model.js and 10 others
````
How do I fix this?

**Comment by luniks** [comment]
Same problem here !
Seems that compatibility with babel 7 is in progress and will be available in **4.x** release (according to the README file).

**Comment by Georgeek** [comment]
@SanjayBanjade delete file ' .babelrc'. This should help.

**Comment by Chang1ng** [comment]
> @SanjayBanjade delete file ' .babelrc'. This should help.

居然删除.babelrc

**Comment by nickmessing** [comment]
you can either install `babel-plugin-syntax-jsx` or just switch to the new preset for JSX: https://github.com/vuejs/jsx

**Comment by liu-and-fei** [comment]
> 为什么删除.babelrc，就可以了

**Comment by luckymore** [comment]
> > 为什么删除.babelrc，就可以了

因为你不用它，，也就不需要它，，，

**Comment by UmbraCi** [comment]
> @SanjayBanjade删除文件'.babelrc'。这应该有所帮助。

why delete this file,can you tell me the reason?
