### ISSUE TITLE
How to register capture event in jsx

### ISSUE THREAD

**Issue by autumnLeaves0** [vuejs/babel-plugin-transform-vue-jsx#170]
use template
`<div @click.capture="handle"></div> `

use createElement
`createElement('div', {
  on:{
    '!click: handle
  }
})`

How to use JSX?

**Comment by autumnLeaves0** [comment]
can use Object Spread (...{}) avoid compiling by JSX, for Example
`<div {...{ is: 'p }}/>`
`<div {...{ on: { click: handle } }}/>`

**Comment by autumnLeaves0** [comment]
Can you provide more JSX grammar support?

**Comment by nickmessing** [comment]
You can either do `<div {...{ on: '!click': handle }} />` or you can try the new JSX implementation https://github.com/vuejs/jsx
