### ISSUE TITLE
How to do non conditional based classes

### ISSUE THREAD

**Issue by dan-gamble** [vuejs/babel-plugin-transform-vue-jsx#18]
I was trying a bunch of things like:

`<div class={['nations', 'detail', { 'loading': this.loading }]}>`
`<div class={'nations', 'detail', { 'loading': this.loading }}>`
`<div class="'nations detail { 'loading': this.loading }">`

etc. to no avail, what is the correct way? :)

**Comment by yyx990803** [comment]
The first one should work, no?

**Comment by dan-gamble** [comment]
Wow, maybe i should check my boolean is true first.. Thanks for being my rubber duck yet again.. 👌
