### ISSUE TITLE
how to write the arguments of the custom directives?

### ISSUE THREAD

**Issue by JE-lee** [vuejs/babel-plugin-transform-vue-jsx#193]
when i use the vue template like below, it works fine with the argument '#srcoll-target'
```html
<v-container id="scroll-target" style="max-height: 400px" >
      <v-row
        v-scroll:#scroll-target="handleScroll"
        style="height: 1000px"
      ></v-row>
</v-container>
```
unfortunately, it can't work with the another way in jsx。 I'm sure about that the problem is the wrong delivering the arguments. is it true ? or how can i transmit the arguments 0f directives in perspective. thank you 
```jsx
 const directives= [
      {
        name: 'scroll',
        value: this.handleScroll.bind(this),
        arguments: {
          ['#scroll-target']: true
        }
      }
 ];
<v-container id="scroll-target" style="max-height: 400px" >
      <v-row
        {...{ directives }}
        style="height: 1000px"
      ></v-row>
</v-container>
```

**Comment by haoqunjiang** [comment]
See https://template-explorer.vuejs.org/#%3Cv-row%0A%20%20v-scroll%3A%23scroll-target%3D%22handleScroll%22%0A%20%20style%3D%22height%3A%201000px%22%0A%3E%3C%2Fv-row%3E%0A

**Comment by haoqunjiang** [comment]
It should be `arg: "#scroll-target"` rather than `arguments: { ['#scroll-target']: true }`
