### ISSUE TITLE
Alias for h... is avoidable?

### ISSUE THREAD

**Issue by skyrpex** [vuejs/babel-plugin-transform-vue-jsx#2]
I know React needs the ```React``` variable available, thus Vue requires something similar but still feels hacky...

Shouldn't it be enough to transpile to ```this.$createElement``` directly? Or couldn't just the plugin to create a variable on the fly and use it?

I'm not sure what Babel plugins are capable of. :smile:

Regards,

**Comment by yyx990803** [comment]
Relying on "this" has scoping issues. This is unavoidable.
