### ISSUE TITLE
react jsx compliant?

### ISSUE THREAD

**Issue by nadimtuhin** [vuejs/babel-plugin-transform-vue-jsx#22]
i was wondering why cant we align with react jsx syntax?

**Comment by nicolas-t** [comment]
I'm also wondering !
It would be easier to use cjsx with https://github.com/jsdf/coffee-react-transform

**Comment by yyx990803** [comment]
Check out https://github.com/vuejs/vue-jsx-adaptor

**Comment by nadimtuhin** [comment]
https://github.com/vuejs/vue-jsx-adaptor is missing :(
