### ISSUE TITLE
Can't access $refs

### ISSUE THREAD

**Issue by 3stacks** [vuejs/babel-plugin-transform-vue-jsx#23]
I'm having issues when trying to access elements in the $refs. The docs don't seem to suggest any different usage.

``` javascript
    render(h) {
        console.log(this.$refs);
        // Returns { element: theNode }
        console.log(this.$refs.element)
        // Returns undefined
        console.log(Object.values(this.$refs));
        // Returns [] (empty array)
        return (
            <div ref="element">
            </div>
        )
    }
```

**Comment by LinusBorg** [comment]
Please provide an actual reproduction on jsfiddle.

**Comment by LinusBorg** [comment]
your example code is confusing. 

You seem to want to access $refs before you actually define it (in the JSX at the end) - of course that can't really work?

Please provide a reproduction on jsfiddle.net

**Comment by 3stacks** [comment]
Yeah it was a lifecycle issue, the reason it was confusing is because I was getting a reference to the refs in $refs. I'm not sure how the lifecycle hooks actually work with this jsx though, where am I supposed to add my `ready` or `init` when using the jsx render.

**Comment by yyx990803** [comment]
This is expected. You can't reference a ref inside a render function before the render function itself is called.
