### ISSUE TITLE
Coffee jsx (cjsx)

### ISSUE THREAD

**Issue by nicolas-t** [vuejs/babel-plugin-transform-vue-jsx#3]
Hi, 

i'm writing my vue component with coffeescript.
With react I used to use cjsx : https://github.com/jsdf/coffee-react-transform

I would love to use something similar for my vue files. Is it planed on any roadmap ?
If I want to do it by myself, do you have any advices on where to start ? (i'm a bit lost in the babel ecosystem)

thanks

**Comment by nickmessing** [comment]
@nicolas-t, because of lack of popularity of CoffeScript I don't think you'll find anyone willing to maintain a coffee version of `vue-jsx`, even the `coffe-react-transform` is deprecated.

**Comment by nicolas-t** [comment]
Yes I think you're right, I stopped using coffee too.

Thanks
