### ISSUE TITLE
[3.2.0] camelCase props issue

### ISSUE THREAD

**Issue by rwu823** [vuejs/babel-plugin-transform-vue-jsx#37]
Suppose a component is designed like this:

```jsx
const Select = {
  name: 'Select',

  props: {
    ...,
    onChange: {
      type: Function,
    },
  },
}
```

And then for use example:

```
<Select onChange={e=>(...)} />
```

That's mean I expect to pass `props` rather than bind `change` event.

**Comment by yyx990803** [comment]
Hmm, I guess this makes it technically a breaking change...

However, I think you can preserve the same component interface simply by changing the internal implementation. Instead of expecting a prop and calling it, emit an event instead:

``` js
// before
this.onChange && this.onChange(e)

// after
this.$emit('change')
```

The consumer of the component don't have to change anything. Would this work in your case?

**Comment by rwu823** [comment]
Sure, `this.$emit` works, but it has a problem the parent component needs assigning a ref name in each `<Select />` every time. That's inconvenient.

```jsx
mounted() {
  this.$refs.select1.on('change', ...)
  this.$refs.select2.on('change', ...)
},
render(h) {
  return (
    <div>
      <Select ref="select1" />
      <Select ref="select2" />
    </div>
  )  
}
```

**Comment by yyx990803** [comment]
No, the parent can keep the exact same usage:

``` js
<Select onChange={()=>{ ... }}/>
```

Because `onChange` is now registered as a component event listener and will listen to `$emit('change')` from the child.

**Comment by rwu823** [comment]
I see. It works great. Thanks so much.

**Comment by codingcampbell** [comment]
Congrats on the recent release, but I have to say this feels like a backwards direction. The `on-` prefix had a nice semantic way of telling you that binding is certainly is an event (either DOM or $emit from component). Now there's just this magic/implicit `onFoo` which _could_ be an event, or could be a prop, maybe component will invoke it directly like in React, maybe it will $emit, who knows?
