### ISSUE TITLE
How to use v-for in jsx

### ISSUE THREAD

**Issue by luckyadam** [vuejs/babel-plugin-transform-vue-jsx#38]
Hello, as title, how can I use `v-for` or `v-if` in jsx!Just like this:
```
<ul class="header_nav_list">
  <li v-for="(item, index) in nav" class={{ header_nav_item: true, active: this.activeNav === item.type }}>{item.name}</li>
</ul>
```
I just got an error `ReferenceError: item is not defined`

**Comment by ktsn** [comment]
You can just use JavaScript loop.

```js
const items = nav.map((item, index) => {
  return <li class={{ header_nav_item: true, active: this.activeNav === item.type }}>{item.name}</li>
})

<ul class="header_nav_list">
  {items}
</ul>
```

**Comment by luckyadam** [comment]
It works!Thank you very much!😬

**Comment by weiluxia1988** [comment]
what about v-if v-else

**Comment by luckyadam** [comment]
@weiluxia1988  maybe like 
```
if (condition) {
   ...
} else {
   ...
}
```

**Comment by ynanzero** [comment]
if like this nested map how code
```
 a: [
        {
            class: 'm-l-20 darkGrey',
            value: '',
            i:[
                {class:'fa fa-angle-down'},
                {class:'fa fa-angle-down'},
            ]

        }
```

**Comment by Maxim-Mazurok** [comment]
> You can just use JavaScript loop.
> 
> ```js
> const items = nav.map((item, index) => {
>   return <li class={{ header_nav_item: true, active: this.activeNav === item.type }}>{item.name}</li>
> })
> 
> <ul class="header_nav_list">
>   {items}
> </ul>
> ```

I've been using this, and I wonder if it makes any sense to provide ` key` with `.map()` approach, or if it's only used for optimization with `v-for`?... https://vuejs.org/guide/essentials/list.html#maintaining-state-with-key
