### ISSUE TITLE
props with on*

### ISSUE THREAD

**Issue by blocka** [vuejs/babel-plugin-transform-vue-jsx#42]
Now that on* are interpreted as events, props that look like that don't get passed through. I very often pass in callbacks like "onSave", etc.

**Comment by blocka** [comment]
Is there any reason these can't be passed as props as well?

**Comment by baiyaaaaa** [comment]
i have the same issue here....~

**Comment by nickmessing** [comment]
@blocka, @baiyaaaaa, `on*` is reserved prefix. You can still use them but instead of using as props you should [emit events](https://vuejs.org/v2/api/#vm-emit) just like in vue with vue-template.
