### ISSUE TITLE
May I ask some questions - about key ref refinfor

### ISSUE THREAD

**Issue by ynanzero** [vuejs/babel-plugin-transform-vue-jsx#43]
key: 'key',
 ref: 'ref',
 refInFor: true,
 what is these three option do ?
 if possible , can gave me a example or url ? let me understand what is they do ,how can i call they ?

**Comment by LinusBorg** [comment]
`key` and `ref` are thoroughly document in the API & Guide.

`refInFor` is used internally only - it's true if a `ref` is defined while in a `v-for` loop, because then, the ref will be created as an array.

**Comment by ynanzero** [comment]
@LinusBorg can  gave me a directive  jsfiddle example . the dos is too simple.

**Comment by LinusBorg** [comment]
Theis is Not a help forum, we have forum.vuejs.org for that.
