### ISSUE TITLE
JSX syntax, does not support Event "on"

### ISSUE THREAD

**Issue by dongfanhua** [vuejs/babel-plugin-transform-vue-jsx#47]
`    <Pagination
                    style={{marginTop: '16px', marginBottom: '16px', float: 'right'}}
                    layout="prev, pager, next"
                    pageSize={this.pagination.pageSize}
                    total={this.total}>
                    onClick={this.handleClick}
                    nativeOnClick={this.handleClick}
                </Pagination>`

babel ====>

`h(
                  _elementUi.Pagination,
                  {
                      style: { marginTop: '16px', marginBottom: '16px', float: 'right' },
                      attrs: { layout: 'prev, pager, next',
                          pageSize: this.pagination.pageSize,
                          total: this.total }
                  },
                  ['onClick=', this.handleClick, 'nativeOnClick=', this.handleClick]
              )`

**Comment by nickmessing** [comment]
<Pagination style={{marginTop: '16px', marginBottom: '16px', float: 'right'}} layout="prev, pager, next" pageSize={this.pagination.pageSize} total={this.total}**>** onClick={this.handleClick} nativeOnClick={this.handleClick} </Pagination>

You have an extra `>`
