### ISSUE TITLE
domPropsInnerHTML doesn't seem to be working

### ISSUE THREAD

**Issue by nddery** [vuejs/babel-plugin-transform-vue-jsx#49]
Can't seem to get `domPropsInnerHTML` to work. When using `createElement` directly it works as expected.

See http://www.webpackbin.com/41TjHAOIM (the App.js tab). You can uncomment the first return (the one using `h`) to see it working.

**Comment by nddery** [comment]
Looking at the code generated from Webpack, it puts the whole `domPropsInnerHTML` as an `attrs`

```js
h(
  'h1',
  {
    attrs: { domPropsInnerHTML: this.msg }
  },
  []
)
```

And the resulting html is

```html
<h1 dompropsinnerhtml="My message &hellip;"></h1>
```

**Comment by nddery** [comment]
So `<p domProps-innerHTML={this.msg} />` works, I can submit a PR to update the README if you'd like.

**Comment by filamin** [comment]
Why? Why need to use '-'?
