### ISSUE TITLE
How do we work with form inputs?

### ISSUE THREAD

**Issue by hailwood** [vuejs/babel-plugin-transform-vue-jsx#50]
Basically as the title says I'm wondering how we are meant to work with form inputs?

As an example here's me trying to work with a checkbox element which is rendered in a loop.

```jsx
/* A test button to trigger it */
<button onClick={e => this.changeGoal(p.id)}>Mark It</button>

/* Text state */
<p>{this.isSelected(p) ? 'checked' : 'unchecked'}</p>

/* The checkbox */
<input type="checkbox" value={p.id} class="changeGoalTest"
    onClick={e => this.changeGoal(p.id)}
    checked={this.isSelected(p)}/>
```

The changeGoal method just updates the selected goal, and the isSelected.. well you get the idea.

Anyway, if I have four items that get spat out, upon clicking on the first `button`  this loops text updates to `checked` and the checkbox is indeed checked.

Clicking on the second `button` the first item reverts it's state and the second item now shows the `checked` text and the checkbox is indeed checked. This holds true for three and four.

However if we click on the `checkboxes` the previously checked boxes do not uncheck however the text above them does change.

I attempted to change my onClick handler to the below version, however it made no difference.
```jsx
onClick={e => {e.preventDefault(); this.changeGoal(p.id)}}`
```

I tried swapping the `onClick` out for `nativeOnClick` and it refused to trigger at all.

**Comment by kimamula** [comment]
I am also facing the same problem.
It is likely that the `checked` attribute of a checkbox cannot be controlled by assigning a variable in JSX.

**Comment by nickmessing** [comment]
@hailwood, @kimamula you need to use `domPropsChecked` instead of `checked` or you can try adding [v-model](https://github.com/nickmessing/babel-plugin-jsx-v-model).
