### ISSUE TITLE
cannot use `style` as custom component prop name

### ISSUE THREAD

**Issue by jaredramirez** [vuejs/babel-plugin-transform-vue-jsx#52]
I have a component Card:
```
const style = {
  ...
};

export default {
  name: 'CardComponent',
  functional: true,
  props: {
    style: Object,
  },
  render: (h, {props, children}) => {
    console.log('style', props.style);
    return (
      <div style={{...style}}>
        {children}
      </div>
    );
  },
};
```
And I reference it in another component SidePanel:
```
import Card from '../components/card';

const styles = {
  ...
  card: {
    height: '200px',
    width: '100px',
  },
};

export default {
  name: 'SidePanelContainer',
  render(h) {
    return (
      <div style={styles.container}>
        <Card style={styles.card}>
          <span>1</span>
        </Card>
      </div>
    );
  },
};
```

From the console.log in CardComponent.render `props.style` is undefined. If I change the prop name then I can access the prop as normal.

This isn't a breaking issue, but for the sake of consistency I'd like to be able to pass custom styles as `style` on both custom and non-custom components alike.

Not sure if this is intended or a bug.
versions:
```
"vue": "^2.1.10",
"babel-plugin-syntax-jsx": "^6.18.0",
"babel-plugin-transform-vue-jsx": "^3.3.0",
"babel-helper-vue-jsx-merge-props": "^2.0.2",
```

**Comment by LinusBorg** [comment]
I would think that this is expected behaviour. in Vue, `style` is a special prop. please see the vnode data content explained [here](https://vuejs.org/v2/guide/render-function.html#The-Data-Object-In-Depth)
