### ISSUE TITLE
Is it a good idea for this babel plugin to provide a browser version?

### ISSUE THREAD

**Issue by reverland** [vuejs/babel-plugin-transform-vue-jsx#53]
when people want to play vue with jsx in browsers (eg. in [vuep](https://github.com/QingWei-Li/vuep)), a standalone babel plugin built for browsers may be useful.

I've built one [myself](https://github.com/reverland/babel-plugin-transform-vue-jsx/commit/4d36bff31080ffc8af09241cc82c806282835787), but I don't know if a good idea for this plugin to provide a browser build. 

Maybe a custom build babel-standalone is a better idea.

https://github.com/babel/babel-standalone/issues/38

Any suggestions?

**Comment by nickmessing** [comment]
That looks like a good idea to me but you didn't have to change it to ES5, we have babel as a dependency anyway so you can just add a task in `package.json` that will build it, without affecting the main codebase.

**Comment by reverland** [comment]
@nickmessing may need babel-loader to bundle it...if I choose webpack to bundle it?

**Comment by nickmessing** [comment]
@reverland, it can be bundled before release just like any other project.

**Comment by reverland** [comment]
@nickmessing I don't understand, can you give an example?

**Comment by nickmessing** [comment]
@reverland, the vue repo itself has `dist` folder that has everything bundled and is there before npm publish so you could do the same with this repo so we have a ES5 bundle in `dist` folder without affecting the source itself.

**Comment by reverland** [comment]
@nickmessing thanks, got it. I forgot how to use loader in webpack cli before. I've updated the repo`

**Comment by nickmessing** [comment]
@reverland, I think you can do a PR for that, looks ok but I guess you should do a separate PR for unused var and another one for the `npm run build`

**Comment by reverland** [comment]
@nickmessing got it, I dont include the `dist`, that looks like is updated when plugin author decide to publish new versions, I'm not sure

**Comment by nickmessing** [comment]
@reverland, yes that's right
