### ISSUE TITLE
how to use keyup.delete event in jsx

### ISSUE THREAD

**Issue by yelingfeng** [vuejs/babel-plugin-transform-vue-jsx#54]
```javascript

<input @keyup.delete="deleteAction">
```

to jsx  

```javascript
<input onKeyup.delete={this.deleteAction}>

```
 
how to do keyup.delete in jsx

**Comment by LinusBorg** [comment]
You can't use modifiers in JSX, they are a feature of the a Vue template syntax. 

You will have to check for this key with moral JavaScript in the handler function.

**Comment by nickmessing** [comment]
@yelingfeng, now you can use [babel-plugin-jsx-syntactic-sugar](https://github.com/nickmessing/babel-plugin-jsx-syntactic-sugar) for that.

**Comment by yelingfeng** [comment]
@nickmessing  thanks very much
