### ISSUE TITLE
support require('xxx.vue') at server side rendering?

### ISSUE THREAD

**Issue by thkdog** [vuejs/babel-plugin-transform-vue-jsx#56]
Why there is not a babel plugin which can transform '.vue' file at runtime at server-side?
This jsx plugin is more like react-style, client side code is not easy to transport to server-side.

**Comment by LinusBorg** [comment]
Because wefocus on SSR-builds with webpack.

You can have a look at this package, maybe that helps: https://www.npmjs.com/package/express-vue

**Comment by thkdog** [comment]
@LinusBorg Thx for the reply. express-vue actually partially solved my problem, but this project seems not ready for production currently, we may still need do something to make it happen.
