### ISSUE TITLE
h auto-inject with vue-class-component

### ISSUE THREAD

**Issue by david50407** [vuejs/babel-plugin-transform-vue-jsx#61]
I got `ReferenceError: h is not defined` inside my `render()` method defined in the class component (with [vue-class-component](https://github.com/vuejs/vue-class-component)) when using v3.4.1.

`h` should be auto-injected [here](https://github.com/vuejs/babel-plugin-transform-vue-jsx/blob/master/index.js#L30), but I don't know why the output of babel missed the part of injection.

.babelrc:

```
{
  "presets": ["es2015"],
  "plugins": [
    "transform-decorators-legacy",
    "transform-class-properties",
    "transform-vue-jsx"
  ]
}
```

part of my babel output:

```
...
_createClass(_default, [{
    key: 'created',
    value: function created() {
      this.fetchData();
    }
  }, {
    key: 'render',
    value: function render() {             // missing injection of `h`
      return h(
...
```

**Comment by nickmessing** [comment]
@david50407, try to push `transform-vue-jsx` before `class-properties` (or even before `decorators-legacy`), they look like changing the class before getting to `vue-jsx`

If that doesn't work please provide an example of the code.

**Comment by david50407** [comment]
@nickmessing Awesome! Thanks for the answer 😄
