### ISSUE TITLE
data-* attribute will not be output

### ISSUE THREAD

**Issue by rwu823** [vuejs/babel-plugin-transform-vue-jsx#7]
I think each dash attribute as well:

```jsx
render(h) {
  return (
    <div data-id="foo" />
  )
}
```

output:
```html
<div></div>
```

It's a solution, but incovenient and doesn't make sense
```jsx
render(h) {
  return (
    <div {...{attrs: {'data-id': 'foo'}}} />
  )
}
```

**Comment by miljan-aleksic** [comment]
@rwu823, custom atributes will be stripped out, it's a jsx thing, not a bug. Seems there is no easy way of declaring them as valid, so I would recommend just using a raw function when required.

**Comment by rwu823** [comment]
@miljan-aleksic 

Thanks for the explain, but in React jsx this is normal way to set attr :(

**Comment by miljan-aleksic** [comment]
@rwu823, is what I have red around about react jsx but seems I'm wrong as Evan applied a fix.
