### ISSUE TITLE
how can i use v-html in JSX

### ISSUE THREAD

**Issue by perluqing** [vuejs/babel-plugin-transform-vue-jsx#72]
like  dangerouslySetInnerHTML in react or  it have anoher ways?

**Comment by LinusBorg** [comment]
https://vuejs.org/v2/guide/render-function.html#The-Data-Object-In-Depth

The example shows it, you have to add it to the data objects `domProps` property.

**Comment by perluqing** [comment]
3Q I just saw JSX didn't see createElement，it`s OK now!

**Comment by halower** [comment]
how can i use v-html in JSX not createElement, too
