### ISSUE TITLE
Functional components options

### ISSUE THREAD

**Issue by nickmessing** [vuejs/babel-plugin-transform-vue-jsx#75]
With functional components coming into vue I'd like to check some potential options of "sugaring" them in jsx.

- [X] `h` auto-inject #76 
- [ ] arrow function component sugar

**`h` auto-inject** change would affect all the components and the solution is to add `h` as a parameter in `render` methods or simply do `const h = arguments[0]`. I can't think of anything that can be broken because of this change.

**Arrow function component sugar** is about being able to define functional components only as using functions. My suggestion is to make it a transform for all exported arrow functions with jsx.
Example:
```js
export const a = ({ props, listeners }) => <div onClick={listeners.click}>{props.msg}</div>
// goes into
export const a = {
  functional: true,
  render: (h, { props, listeners }) => <div onClick={listeners.click}>{props.msg}</div>
}
```
Is that a valid option? This is actually a breaking change, is that considerable @yyx990803?

**Comment by yyx990803** [comment]
Auto injection looks good - not sure about the functional transform though, that seems to be the responsibility of a separate plugin.

**Comment by nickmessing** [comment]
As discussed in #77, going to move this to a separate project
