### ISSUE TITLE
Component bind event doesn't work

### ISSUE THREAD

**Issue by rwu823** [vuejs/babel-plugin-transform-vue-jsx#8]
```jsx
impornt Child from './child'

...
methods: {
  handleClick(){

  }
},

render(h) {
  <div>
    <Child on-click={this.handleClick}  /> 
  </div>
}
```

**Comment by yyx990803** [comment]
This is not this plugin's problem - component event listeners only listen to component events emitted by that component (e.g. `this.$emit('click')` from within that component). It is up to the component to decide whether it wants to proxy native events.
