### ISSUE TITLE
this.$scopedSlots.default is not a function

### ISSUE THREAD

**Issue by gentean** [vuejs/babel-plugin-transform-vue-jsx#82]
```
render: function (createElement) {
            return createElement('div', [
                this.$scopedSlots.default({
                    text: '123'
                })
            ])
        }
```

**Comment by nickmessing** [comment]
@gentean, can you post a more detailed info about how you pass slots?

**Comment by chaishi** [comment]
Hi,@gentean 
I encountered the same problem, have you solved it ?
-----------------------------------
render (createElement) {
    return createElement('thead', [
      createElement('tr', this.cols.map(item => {
        return createElement('th', [
          this.$scopedSlots.default({
            item: item
          })
        ])
      }))
    ])
  }
-------------------------------------

**Comment by nickmessing** [comment]
@chaishi, where did you copy this code from?

P.S. this code has no JSX, it's plain JS

**Comment by nickmessing** [comment]
Closed due to inactivity, if you experience the same problem feel free to open a new issue.

**Comment by Skura23** [comment]
> you can add a key props to table like this:
> 
> <el-table key='aTable' v-if="firstTabActive"></el-table>

**Comment by liuen12** [comment]
这个是问题 该怎么解决呢   我也遇到这个问题了

**Comment by seahurt** [comment]
我遇到了同样的错误，代码是切换两个el-table的显示，从第一个切到第二个的时候没问题，切回到第一个的时候就报错，按照 @Skura23 的回答，添加了key就OK了
