### ISSUE TITLE
"Unknown custom element" when use "<component>" in render function

### ISSUE THREAD

**Issue by fayfang** [vuejs/babel-plugin-transform-vue-jsx#85]
like the screenshot below , when I use "component" in render function as JSX grammar
![15c79430-c657-470a-8da5-74a4a7fcdc01](https://user-images.githubusercontent.com/15612884/27906476-44a1522e-6276-11e7-99c0-71843717c009.png)
![2060fb86-7969-4286-9306-56d9b9fe9bc6](https://user-images.githubusercontent.com/15612884/27906490-518e47bc-6276-11e7-8888-21b16bc87292.png)

**Comment by nickmessing** [comment]
That is a part of vue template language, the alternative to `<component :is="test-dom" />` would be:
```js
const Comp = this['test-dom']
return <Comp />
```

**Comment by koresar** [comment]
Another solution for vue JSX dynamic component instantiation:
```js
render () {
  // creating component instance
  const returnDom = something === true ? <Foo a="b" /> : <Bar c="d" />

  return (
    <div>
      {returnDom}
    </div>
  )
}
```

**Comment by JimmyLv** [comment]
@nickmessing `<this['test-dom'] />` does not work and can't compile the syntax at all:

![image](https://user-images.githubusercontent.com/4997466/48459792-b6419800-e806-11e8-8095-3af7b9bea88d.png)
