### ISSUE TITLE
domPropsInnerHTML incorrect markup

### ISSUE THREAD

**Issue by alidcastano** [vuejs/babel-plugin-transform-vue-jsx#90]
I'm trying to render HTML using JSX. 

For example: 
```
  <div>
      <div domPropsInnerHTML={ this.body } />
 </div>
```

However I'm getting the following error: 

```
The client-side rendered virtual DOM tree is not matching server-rendered content. This is likely caused by incorrect HTML markup, for example nesting block-level elements inside <p>, or missing <tbody>. Bailing hydration and performing full client-side render.
```

When I try the same exact HTML using the v-html directive in a vue template, the error disapears.

```
<div>
  <div v-html="body">
</div>
```

I would resort to using that, but I'm trying to use create a [helper component](https://github.com/nuxt-community/nuxtent/blob/master/lib/plugin.js#L11) for `nuxtent` that based on data renders a dynamic component or HTML at runtime, so that vue components could easily be used inside markdown.

**Comment by nickmessing** [comment]
Hello @alidcastano, thank you for the report but it's not enough information, can you please provide a link to repository where this happens?

**Comment by alidcastano** [comment]
Here's the repo: https://github.com/nuxt-community/nuxtent.

You can see the error in action if you run the docs. Go to any documentation page and press refresh. 

```
cd docs
npm install
npm run dev
```

And I provided a link to the exact place in the source code above.

**Comment by alidcastano** [comment]
@nickmessing Any update on this?

**Comment by nickmessing** [comment]
@alidcastano, sorry, totally forgot about it, will take a look in the next hours.

**Comment by alidcastano** [comment]
Awesome, thanks!

**Comment by alidcastano** [comment]
@nickmessing Did you have a chance to look into it?

**Comment by nickmessing** [comment]
@alidcastano, unfortunately no, had really busy time at work, but looks like I will have time today

**Comment by whtsky** [comment]
Any updates on this?
Found that writing 
```jsx
<div domProps={{ innerHTML: content }} />
```
Solves the problem

**Comment by whtsky** [comment]
Found that
```js
h('pre', {
  domProps: {
    innerHTML: 'content',
  },
})
```

works and
```js
h('pre', {
  domProps: {
    innerHTML: 'content',
  },
}, [])
```
doesn't.

**Comment by nickmessing** [comment]
Oh, thank you for that finding, I didn't have time for this issue but since you tracked it down it can be easily fixed, thank you for the effort @whtsky.

**Comment by nickmessing** [comment]
@alidcastano, are you sure `v-html` works?
I get that error on both:
```
<template>
  <div v-html="'<h1>Hey</h1>'">Hello</div>
</template>
```
and
```
<script>
export default {
  render () {
    return <div domPropsInnerHTML={`<h2>Hey</h2>`}>Hello</div>
  }
}
</script>
```
Looks like an SSR issue.

**Comment by nickmessing** [comment]
Discussion continuer ad vuejs/vue#6519
