### ISSUE TITLE
h of render in a .tsx file

### ISSUE THREAD

**Issue by peterchealse** [vuejs/babel-plugin-transform-vue-jsx#93]
verion: 3.5.0 
h is not defined if I write a single file component in tsx.
if i use *.vue, it works well.
<pre>
import Vue from 'vue';
import { component, Prop, Watch } from 'vue-property-decorator';
@Component
export default class Test extends Vue {
  text = '';
  render() {
    return (
     &lt;span> {this.text}&lt;/span>
    );
  }
}
</pre>

babelrc: 
<pre>{
  "presets": ["es2015", "stage-2"],
  "plugins": [
    "transform-runtime",
    "transform-vue-jsx"
  ],  
"comments": false
}`</pre>

webpack loader:
<pre>{
        test: /\.vue$/,
        loader: 'vue-loader',
        options: vueLoaderConfig
      },
      {
        test: /\.ts(x?)$/,
        loader: 'babel-loader!ts-loader',
      },
      {
        test: /\.js$/,
        loader: 'babel-loader',
        include: [resolve('src')]
      }</pre>

i am thinking if it is caused by the loader.....

**Comment by nickmessing** [comment]
@peterchealse, unfortunately there's no way around that in TypeScript at the moment so you have to use `render (h) { return <div> }`
