### ISSUE TITLE
dangerouslySetInnerHTML not work totally

### ISSUE THREAD

**Issue by zzzgit** [vuejs/babel-plugin-transform-vue-jsx#94]
`<div dangerouslySetInnerHTML={{__html: item.detailInfo}}></div>`

it will be an empty element after compiled

**Comment by LinusBorg** [comment]
That's a React prop, not a JSX functionality, and therefore not available in Vue. You should use a domProp instead, it's documented in the README.

**Comment by zzzgit** [comment]
thanks very much

**Comment by nickmessing** [comment]
@LinusBorg, looks like it's a bug not related to `jsx`, more like it's related to `ssr` itself
