### ISSUE TITLE
How use props component start "on"?

### ISSUE THREAD

**Issue by kolesoffac** [vuejs/babel-plugin-transform-vue-jsx#95]
I use [switch component](http://element.eleme.io/#/en-US/component/switch) in jsx-template and use "on-text" prop. It parse how event "on".

How use it?

**Comment by Akryum** [comment]
Use destructuring:

```jsx
const data = {
  props: {
    onText: 'bar',
  },
}

return <MyComponent foo={bar} {...data} />
```

**Comment by kolesoffac** [comment]
many thanks!
